# Generated by Django 4.2.19 on 2025-03-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
    ]
