# Generated by Django 4.2.20 on 2025-03-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_answercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='purposes',
            field=models.ManyToManyField(blank=True, related_name='answers', to='problems.answerpurpose'),
        ),
    ]
